services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    environment:
      STORAGE_BACKEND: local
      QUEUE_BACKEND: local


  worker:
    build: ./worker
    volumes:
      - ./storage:/app/storage
    environment:
      STORAGE_BACKEND: local
      QUEUE_BACKEND: local
